name: isolate_manager_generator
description: "The generator for the isolate_manager"
version: 0.3.0
homepage: https://github.com/lamnhan066/isolate_manager_generator

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.4.0
  args: ^2.5.0
  isolate_manager:
    git:
      url: https://github.com/4Q-s-r-o/isolate_manager.git
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.15
  very_good_analysis: ^10.0.0
